name: Build and deploy Node.js app to Azure Web App - pa200HW2PaasWeb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Install Azure CLI and jq
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          sudo apt-get install -y jq

      - name: Upload to Azure Blob Storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          az storage blob upload-batch -d testconthw2 --account-name $AZURE_STORAGE_ACCOUNT --account-key $AZURE_STORAGE_KEY -s ./build

      - name: Update asset-manifest, precache-manifest, and index.html
        run: |
          BLOB_URL="https://astorageaccthw2.blob.core.windows.net/testconthw2"
          ASSET_MANIFEST="./build/asset-manifest.json"
          INDEX_HTML="./build/index.html"
          PRECACHE_MANIFEST=$(ls ./build/precache-manifest.*.js)

          # Update asset-manifest.json
          jq '.files |= map_values($BLOB_URL + .)' "$ASSET_MANIFEST" --arg BLOB_URL "$BLOB_URL" > temp.json
          if [ -s temp.json ]; then
            mv temp.json "$ASSET_MANIFEST"
          else
            echo "Failed to update asset-manifest.json"
            exit 1
          fi

          # Update precache-manifest.js
          if ! sed -i "s|\"url\": \"/static/|\"url\": \"${BLOB_URL}/static/|g" "$PRECACHE_MANIFEST"; then
            echo "Failed to update precache-manifest.js"
            exit 1
          fi

          # Update index.html
          if ! sed -i "s|/static/js/|${BLOB_URL}/static/js/|g" "$INDEX_HTML" || ! sed -i "s|/static/css/|${BLOB_URL}/static/css/|g" "$INDEX_HTML"; then
            echo "Failed to update index.html"
            exit 1
          fi


      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7AADED415E27425893EE262F949FD5E6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F3360995AB94EA98C38D68AE5CC3A05 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_09696950CC484DF093D57F73902482E8 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pa200HW2PaasWeb'
          slot-name: 'Production'
          package: .
