# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - pa200HW2PaasWeb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Update asset links in index.html
        run: |
          sed -i 's|/static/css/main\..*\.css|https://astorageaccthw2.blob.core.windows.net/hw2container/main.css|g' ./build/index.html
          sed -i 's|/static/js/2\..*\.chunk\.js|https://astorageaccthw2.blob.core.windows.net/hw2container/2.js|g' ./build/index.html
          sed -i 's|/static/js/main\..*\.chunk\.js|https://astorageaccthw2.blob.core.windows.net/hw2container/main.js|g' ./build/index.html

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7AADED415E27425893EE262F949FD5E6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F3360995AB94EA98C38D68AE5CC3A05 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_09696950CC484DF093D57F73902482E8 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pa200HW2PaasWeb'
          slot-name: 'Production'
          package: .
          